spring:
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
    # https://stackoverflow.com/a/67678945/548473
    defer-datasource-initialization: true
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/secure_env
    username: access_su
    password: Jnnheljdghfdtlys[?
#    username: postgres
#    password: postgres
    driver-class-name: org.postgresql.Driver