server:
  port: 8081
spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:voting
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2.console.enabled: true
  data.rest:
    returnBodyOnCreate: true