server:
  port: 8989
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://10.7.118.29:5432/efr_14
    username: accreditive_service_excamad
    password: accreditive_service_excamad
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate  # вместо update для production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    database:
      type: postgres
      schema-update: true
    history-level: audit
    job-executor:
      enabled: true
    filter:
      create: All tasks