server:
  port: 8989

spring:
  datasource:
    url: jdbc:postgresql://10.7.118.29:5432/efr_14
    username: accreditive_service_excamad
    password: accreditive_service_excamad
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update

# Конфигурация Camunda
camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    database:
      type: postgres
      schema-update: true
    history-level: audit
    job-executor:
      enabled: true
    jdbc:
      batch-processing: false
    webapp:
      enabled: true
    rest:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: mappings,health,info
      base-path: /actuator
  endpoint:
    mappings:
      enabled: true