/*
 * 
 * Публичный API для подпроцесса 'Оформление заявки на кредит. 4 этап - выдача кредита'
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ru.schoolservice.arm.config;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.springframework.validation.annotation.Validated;

import java.util.Objects;

/**
 * Данные письма Минсельхоза России
 */
@SuppressWarnings("all")
@Validated
public class InsuranceProgramRisk {
    @JsonProperty("id")
    private Long id = null;

    @JsonProperty("insuranceCode")
    private String insuranceCode = null;

    @JsonProperty("riskCode")
    private String riskCode = null;

    @JsonProperty("riskAbsCode")
    private String riskAbsCode = null;


    /**
     * Создает пустой экземпляр класса
     */
    public InsuranceProgramRisk() {}

    /**
     * Создает экземпляр класса
     * 
     * @param id Идентификатор запроса
     * @param insuranceCode Номер письма Минсельхоза России
     * @param riskCode дата письма Минсельхоза России
     * @param riskAbsCode дата письма Минсельхоза России
     */
    public InsuranceProgramRisk(Long id, String insuranceCode, String riskCode, String riskAbsCode) {
        this.id = id;
        this.insuranceCode = insuranceCode;
        this.riskCode = riskCode;
        this.riskAbsCode = riskAbsCode;
    }

    /**
     * Идентификатор запроса
     *
     * @return Идентификатор запроса
     */
    


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }


    /**
     * Номер письма Минсельхоза России
     *
     * @return Номер письма Минсельхоза России
     */
    


    public String getInsuranceCode() {
        return insuranceCode;
    }

    public void setInsuranceCode(String insuranceCode) {
        this.insuranceCode = insuranceCode;
    }


    /**
     * дата письма Минсельхоза России
     *
     * @return дата письма Минсельхоза России
     */
    


    public String getRiskCode() {
        return riskCode;
    }

    public void setRiskCode(String riskCode) {
        this.riskCode = riskCode;
    }


    /**
     * дата письма Минсельхоза России
     *
     * @return дата письма Минсельхоза России
     */
    


    public String getRiskAbsCode() {
        return riskAbsCode;
    }

    public void setRiskAbsCode(String riskAbsCode) {
        this.riskAbsCode = riskAbsCode;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InsuranceProgramRisk insuranceProgramRisk = (InsuranceProgramRisk) o;
        return Objects.equals(this.id, insuranceProgramRisk.id) &&
                Objects.equals(this.insuranceCode, insuranceProgramRisk.insuranceCode) &&
                Objects.equals(this.riskCode, insuranceProgramRisk.riskCode) &&
                Objects.equals(this.riskAbsCode, insuranceProgramRisk.riskAbsCode);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, insuranceCode, riskCode, riskAbsCode);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InsuranceProgramRisk {\n");
        
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    insuranceCode: ").append(toIndentedString(insuranceCode)).append("\n");
        sb.append("    riskCode: ").append(toIndentedString(riskCode)).append("\n");
        sb.append("    riskAbsCode: ").append(toIndentedString(riskAbsCode)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

